// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;
public class Easy : MonoBehaviour, IGameDifficulty
{

	public Easy () {
	}

	public void instantiate() {
		EnemyAttack._setAttackDamage (5);
		PlayerShooting._setDamagePerShot (20);
	}

	public void calculateScore() {

			Debug.Log("Easy : " + gameObject.GetComponents<EnemyHealth> ());
			if (gameObject.CompareTag ("Zombunny")) {
				//gameObject.GetComponent<EnemyHealth> ().scoreValue += 5;
				ScoreManager.score += (gameObject.GetComponent<EnemyHealth> ().scoreValue + 5);
			} 
			if (gameObject.CompareTag ("Zombear")) {
				//gameObject.GetComponent<EnemyHealth> ().scoreValue += 5;
				ScoreManager.score += (gameObject.GetComponent<EnemyHealth> ().scoreValue + 5);
			}
			if (gameObject.CompareTag ("Hellephant")) {
				//gameObject.GetComponent<EnemyHealth> ().scoreValue += 10;
				ScoreManager.score += (gameObject.GetComponent<EnemyHealth> ().scoreValue + 10);
			}
	}
}

